# Framework to model host compatibility mapping
# Each framework entry lists the supported model hosts
# Available model hosts: openai, google, ollama, transformers
# Don't modify below contents

OllamaFramework:
  hosts:
    - ollama

OpenAIFramework:
  hosts:
    - openai
    - ollama
    - google
    - vllm

GoogleFramework:
  hosts:
    - google

MarvinFramework:
  hosts:
    - openai
    - ollama

LlamaIndexFramework:
  hosts:
    - openai
    - ollama
    - google
    - vllm

InstructorFramework:
  hosts:
    - openai
    - ollama
    - google
    - vllm

MirascopeFramework:
  hosts:
    - openai
    - google
    #- ollama(not working)

LMFormatEnforcerFramework:
  hosts:
    - transformers
  
LangchainToolFramework:
  hosts:
    - openai
    - google
    - ollama
    - vllm

LangchainParserFramework:
  hosts:
    - openai
    - google
    - ollama
    - vllm