# Framework to model host compatibility mapping
# Each framework entry lists the supported model hosts
# Available model hosts: openai, google, ollama, transformers
# Don't modify below contents

VanillaOllamaFramework:
  hosts:
    - ollama

VanillaOpenAIFramework:
  hosts:
    - openai
    - ollama

VanillaGoogleFramework:
  hosts:
    - google

MarvinFramework:
  hosts:
    - openai
    - ollama

LlamaIndexFramework:
  hosts:
    - openai
    - ollama

InstructorFramework:
  hosts:
    - openai
    - ollama
    - google

MirascopeFramework:
  hosts:
    - openai
    - ollama

LMFormatEnforcerFramework:
  hosts:
    - transformers